### ISSUE TITLE
FizzBuzz Challenge Hacktoberfest Style!

### ISSUE THREAD

**Issue by SheW0lf** [SheW0lf/Cats_Bats_Spiders#2]
Write a program that prints the numbers from 1 to 100, but for numbers that are multiples of 3, print 'cats' instead of the number, for numbers that are multiples of 5 print 'bats' instead of the number, and for numbers that are multiples of both 3 and 5 print 'spiders'.

You can write this program in any language you choose! Check out the Code for more details about the project, and how to contribute.

Feel free to ask questions if you need help!

Have fun, and happy hacking!

**Comment by beingadityak** [comment]
Hi @SheW0lf , Can I start working on this issue?

**Comment by SheW0lf** [comment]
@beingadityak of course you can! Everyone is welcome! check out the Readme for more info if you need it.

**Comment by rbo13** [comment]
Hi @SheW0lf, I've added the golang implementation for the challenge here: https://github.com/SheW0lf/Cats_Bats_Spiders/pull/7

**Comment by RedYetiCo** [comment]
Hey @SheW0lf, just PR'd my PHP implementation!
